### ISSUE TITLE
Plugin eZProtector v4.4.2 generated an exception

### ISSUE THREAD

**Issue by RubenBarrionuevo** [DoNotSpamPls/eZProtector#34]
**Describe the bug**
A clear description of what the bug is.
The bug does not seem to throw any errors in the game, but if it shows these errors in console

**To Reproduce**
1. Run server
2. the number of users on the server is greater than 2 and they start talking

**Screenshots**
![image](https://user-images.githubusercontent.com/24832320/49157426-0b5dcd80-f320-11e8-9948-41f2d6874596.png)

**Server Version:**
Spigot 1.13.2

> [14:57:38] [Server thread/WARN]: [eZProtector] Plugin eZProtector v4.4.2 generated an exception whilst handling plugin message
java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use )
	at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:474) ~[paper.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.plugin.messaging.StandardMessenger.isOutgoingChannelRegistered(StandardMessenger.java:401) ~[paper.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:514) ~[paper.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1213) ~[paper.jar:git-Spigot-2474d93-e693496]
	at com.github.donotspampls.ezprotector.listeners.ByteMessageListener.onPluginMessageReceived(ByteMessageListener.java:51) ~[?:?]
	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:427) ~[paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2468) ~[paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45) ~[paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9) ~[paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[paper.jar:git-Spigot-2474d93-e693496]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [paper.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [paper.jar:git-Spigot-2474d93-e693496]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by Lagger625** [comment]
I followed the stacktrace, and it seems like setting schematica's block to false in the config avoids this exception. It doesn't makes a difference singe Forge still isn't released for 1.13... but it will be soon.

**Comment by RubenBarrionuevo** [comment]
Ohh thanks it's works

**Comment by DoNotSpamPls** [comment]
It's a known issue - I just haven't gotten around to fixing it, as other stuff has had higher priority

**Comment by DoNotSpamPls** [comment]
Resolved in 1134a4e and 241b95c
