### ISSUE TITLE
eZProtector v4.1.6 generated an exception while executing task 123

### ISSUE THREAD

**Issue by TKwSni** [DoNotSpamPls/eZProtector#4]
**Describe the bug**
```
[eZProtector] Plugin eZProtector v4.1.6 generated an exception while executing task 123
java.lang.NullPointerException: null
	at ez.plugins.dan.SpigotUpdater.SpigotUpdater.run(SpigotUpdater.java:102) ~[?:?]
	at ez.plugins.dan.SpigotUpdater.SpigotUpdater.<init>(SpigotUpdater.java:80) ~[?:?]
	at ez.plugins.dan.SpigotUpdater.UpdateChecker.checkUpdate(UpdateChecker.java:39) ~[?:?]
	at ez.plugins.dan.Main$1.run(Main.java:58) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

```

**To Reproduce**
1. Start the server
2. Wait few seconds
3. Profit

**Server Version:**
1.12.2

**Comment by DoNotSpamPls** [comment]
This bug has already been reported multiple times. It has been fixed in the development versions and will be released to Spigot soon.
