### ISSUE TITLE
Error on startup with Velocity

### ISSUE THREAD

**Issue by SmallSansSerif** [DoNotSpamPls/eZProtector#67]
Velocity 3.0.1
ezProtector build from actions: https://github.com/Elytrium/eZProtector/actions/runs/1397369552

**Describe the bug**
[15:09:26 ERROR]: Couldn't pass ProxyInitializeEvent to ezprotector
java.lang.NoClassDefFoundError: net/kyori/text/Component
        at com.github.donotspampls.ezprotector.velocity.Main.onProxyInitialization(Main.java:60) ~[?:?]
        at com.github.donotspampls.ezprotector.velocity.Lmbda$10.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.0.1.jar:3.0.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:585) ~[velocity-3.0.1.jar:3.0.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:466) ~[velocity-3.0.1.jar:3.0.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.text.Component
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:83) ~[velocity-3.0.1.jar:3.0.1]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:60) ~[velocity-3.0.1.jar:3.0.1]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 8 more

**Comment by mdxd44** [comment]
> 
> 
> Velocity 3.0.1 ezProtector build from actions: https://github.com/Elytrium/eZProtector/actions/runs/1397369552
> 
> **Describe the bug** [15:09:26 ERROR]: Couldn't pass ProxyInitializeEvent to ezprotector java.lang.NoClassDefFoundError: net/kyori/text/Component at com.github.donotspampls.ezprotector.velocity.Main.onProxyInitialization(Main.java:60) ~[?:?] at com.github.donotspampls.ezprotector.velocity.Lmbda$10.execute(Unknown Source) ~[?:?] at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.0.1.jar:3.0.1] at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:585) ~[velocity-3.0.1.jar:3.0.1] at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:466) ~[velocity-3.0.1.jar:3.0.1] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?] at java.lang.Thread.run(Thread.java:834) [?:?] Caused by: java.lang.ClassNotFoundException: net.kyori.text.Component at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:83) ~[velocity-3.0.1.jar:3.0.1] at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:60) ~[velocity-3.0.1.jar:3.0.1] at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] ... 8 more

This already fixed, currently in ezprotector I need to completely recode and test all functions

**Comment by mdxd44** [comment]
Within a week I plan to finish
